sandbox/django-basics/guestbook/urls.py
from django.urls import path
from . import views

app_name="guestbook"
urlpatterns = [
    path("new/", views.create_guest, name="new"),
    path("", views.list_guest, name="list"),
]

sandbox/django-basics/guestbook/models.py
from django.db import models

# Create your models here.
class Guest(models.Model):
    name = models.CharField("ФИО", max_length=100)
    message = models.TextField("Сообщение", max_length=1500)
    created_at = models.DateTimeField("Созданое говно", auto_now_add=True)
    
    def __str__(self):
        return f"{self.name} -  <{self.message}>"

sandbox/django-basics/guestbook/forms.py
from django import forms
from django.core.exceptions import ValidationError

class GuestForm(forms.Form):
    name = forms.CharField(label="Your name", max_length=50)
    message = forms.CharField(label="Your message", widget=forms.Textarea, max_length=1000)

    def clean_name(self):
        value = self.cleaned_data["name"].strip()
        if len(value.split()) < 2:
            raise ValidationError("Укажите имя и фамилию.")
        return value

sandbox/django-basics/guestbook/views.py
from django.shortcuts import render
from .forms import GuestForm
from .models import Guest

def create_guest(request):
    if request.method == "POST":
        form = GuestForm(request.POST)
        if form.is_valid():
            # ручное сохранение в БД через модель
            Guest.objects.create(
                name=form.cleaned_data["name"],
                message=form.cleaned_data["message"],
            )
            return render(
                request,
                "guestbook/new.html",
                {"form": GuestForm(), "sent": True}  # <<< в шаблоне проверяешь sent
            )
    else:
        form = GuestForm()

    return render(request, "guestbook/new.html", {"form": form, "title": "Guestbook"})

    
        
def list_guest(request):
    guests = Guest.objects.order_by("-created_at")[:50]
    return render(request, "guestbook/list.html", {
        "title": "Pizda",
        "guests": guests
    })

sandbox/django-basics/guestbook/templates/guestbook/list.html
{% extends "pages/base.html" %}
{% block pages_content %}
<h1>Последние заявки</h1>
тут будут показываться все сообщения от пользователей. 

<p>Страница список -  {{ title }} </p>


<table border="1" cellpadding="6">
  <tr>
    <th>Когда</th><th>ФИО</th><th>Сообщение</th>
  </tr>
  {% for x in guests %}
  <tr>
    <td>{{ x.created_at|date:"Y-m-d H:i" }}</td>
    <td>{{ x.name }}</td>
    <td>{{ x.message|linebreaksbr }}</td>
  </tr>
  {% empty %}
  <tr><td colspan="4">Пока ничего</td></tr>
  {% endfor %}
</table>

<p><a href="{% url 'guestbook:new' %}">отправить сообщение</a></p>
{% endblock %}

sandbox/django-basics/guestbook/templates/guestbook/new.html
{% extends "pages/base.html" %}
{% block pages_content %}
<h1>Новое сообщение от пользователя</h1>

<p>{{ title }}</p>

{% if sent %}
  <div style="border:1px solid #4caf50;padding:10px;margin:10px 0;">
    Сообщение доставлено {{ data.name }} !
  </div>
{% endif %}

<form method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}

  <div>
    <label for="{{ form.name.id_for_label }}">ФИО</label><br>
    {{ form.name }} {{ form.name.errors }}
  </div>

  <div>
    <label for="{{ form.message.id_for_label }}">Сообщение</label><br>
    {{ form.message }} {{ form.message.errors }}
  </div>


  <button type="submit">отправить</button>
</form>

<p>
    <a href="{% url 'guestbook:list' %}">просмотреть последние сообщения</a>
</p>

{% endblock %}