sandbox/django-basics/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"
urlpatterns = [
    path("", views.home, name="home"),
    path("time/", views.time, name="time"),
    path("hello/", views.hello, name="hello"),
]

sandbox/django-basics/pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone


# Create your views here.
def home(request):
    return render(request, "pages/home.html", {"title": "Home page"})

def time(request):
    
    return render(request, "pages/time.html",{"title": "Time page", "current_time": timezone.now()})

def hello(request): 
    return HttpResponse("stalker")

sandbox/django-basics/pages/templates/layout/_nav.html
    <nav>
      <a href="{% url 'pages:home' %}">Главная</a> |
      <a href="{% url 'pages:time' %}">Текущее время</a> |
      <a href="{% url 'pages:hello'%}">Сказать привет</a> |
      <a href="{% url 'info:about'%}">О нас</a> |
      <a href="{% url 'info:subscribe'%}">Подписка</a> |
      <a href="{% url 'info:contacts'%}">Контакты</a> |
      <a href="{% url 'info:callback'%}">Обратная связь</a> |
      <a href="http://127.0.0.1:8000/leads/">Оставить лид в БД</a> |
    </nav>

sandbox/django-basics/pages/templates/pages/base.html
<!doctype html>
<html lang="ru">
  <body>
    {% include 'layout/_nav.html' %}  
    <hr>
    {% block pages_content %}{% endblock %}
  </body>
</html>

sandbox/django-basics/pages/templates/pages/home.html
{% extends "./base.html" %}
{% block pages_content %}
  <h1>Домашняя (pages) - {{title}}</h1>
  <p>Это главная страница приложения pages под /pages/</p>
{% endblock %}

sandbox/django-basics/pages/templates/pages/time.html
{% extends "./base.html" %}
{% block pages_content %}
  <h1>{{ title |default:"Which time is it now ?"}}</h1>
  <p>Сегодняшне время: {{current_time}}</p>
  <a href="{% url 'info:about' %}">Подробнее о сайте</a>
{% endblock %}